title: Wandercoin
description: Minimalist currency converter for iOS and Android — privacy-first, no tracking, no ads.
theme: jekyll-theme-minimal

permalink: /:basename/

include:
  - privacy.md
  - impressum.md
  - index.md
